version: '3.3'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bogdanislaugh/lab4:django-app
    container_name: django-app
    networks: 
      - public
    ports: 
      - 80:8000
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: bogdanislaugh/lab4:django-monitor
    container_name: django-monitor
    networks: 
      - public

networks: 
  public:
    driver: bridge
